apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform/cluster add-ons managed by Argo CD
  sourceRepos:
    - '*'                # tighten later
  destinations:
    - namespace: '*'
      name: in-cluster
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
