apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../projects/platform.yaml
  - ../../projects/services.yaml


  # dev secrets for Grafana
  - ../../apps/platform/monitoring/secrets/grafna-admin.secret.yaml
  - ../../apps/platform/monitoring/secrets/grafna-oidc.secret.yaml
  
  # Platform apps
  - ../../apps/platform/networking/argocd-ingress/application.yaml
  - ../../apps/platform/cert-manager/application.yaml
  - ../../apps/platform/monitoring/application.yaml


  # Services (can point at prod overlays or prod values)
  - ../../apps/services/currency-exchange/application.yaml
patches:
  - target:
      kind: Application
      name: currency-exchange
    patch: |-
      - op: replace
        path: /spec/source/helm/valueFiles/0
        value: values-dev.yaml

  - target: { kind: Ingress, name: argocd, namespace: argocd }
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: devcluster-gw.eastus.cloudapp.azure.com