apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Namespaces
  - ./namespaces/monitoring-namespace.yaml
  - ./namespaces/dev-services.yaml

  # Projects
  - ./projects/platform.yaml
  - ./projects/services.yaml

  # Dev secrets for Grafana
  - ./platform/monitoring/secrets/grafana-admin.secret.yaml
  - ./platform/monitoring/secrets/grafana-oidc.secret.yaml

  # Platform apps
  # - ./platform/networking/argocd-ingress/ingress.yaml
  - ./platform/monitoring/application.yaml

  # Services
  - ./services/currency-exchange/application.yaml

patches:
  # Point service app to dev values
  - target:
      kind: Application
      name: currency-exchange
    patch: |-
      - op: replace
        path: /spec/source/helm/valueFiles/0
        value: values-dev.yaml

  # Ensure Argo CD ingress uses nginx class (hostless, path-based)
  - target:
      kind: Ingress
      name: argocd
      namespace: argocd
    patch: |-
      - op: add
        path: /spec/ingressClassName
        value: nginx
      - op: remove
        path: /spec/rules/0/host
