apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  
  # Namespaces
  - ./namespaces/monitoring-namespace.yaml
  - ./namespaces/dev-services.yaml

  # Projects
  - ./projects/platform.yaml
  - ./projects/services.yaml

  # Dev secrets for Grafana
  - ./platform/monitoring/secrets/grafana-admin.secret.yaml
  - ./platform/monitoring/secrets/grafana-oidc.secret.yaml

  # Platform apps
  - ./platform/networking/argocd-ingress/application.yaml
  - ./platform/cert-manager/application.yaml
  - ./platform/monitoring/application.yaml


  # Services (can point at prod overlays or prod values)
  - ./services/currency-exchange/application.yaml
patches:
  - target:
      kind: Application
      name: currency-exchange
    patch: |-
      - op: replace
        path: /spec/source/helm/valueFiles/0
        value: values-dev.yaml

  - target: { kind: Ingress, name: argocd, namespace: argocd }
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: devcluster-kengw.eastus.cloudapp.azure.com

  - target: { kind: AppProject, name: services, namespace: argocd }
    patch: |
      - op: replace
        path: /spec/destinations/0/namespace
        value: dev-services