apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv
spec:
  provider:
    azurekv:
      tenantId: "<YOUR_TENANT_ID>"
      vaultUrl: "https://<YOUR_KV_NAME>.vault.azure.net"
      authType: "WorkloadIdentity"
