apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"   # ensure project exists before apps
spec:
  description: Platform/cluster add-ons managed by Argo CD
  # Only allow known sources (add more as you adopt them)
  sourceRepos:
    - https://charts.jetstack.io
    - https://prometheus-community.github.io/helm-charts
    - https://github.com/KiemaKennedy/platform-apps.git
  # Where deploys are allowed (add more clusters/namespaces as needed)
  destinations:
    - name: in-cluster
      namespace: '*'
  # Platform often needs cluster-scoped writes for operators/CRDs
  clusterResourceWhitelist:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: cert-manager.io
      kind: ClusterIssuer
    - group: ""
      kind: Namespace
